---
remote_theme: mmistakes/so-simple-theme@3.2.0
title: Sloan's Homepage
description: In this project I am building a Business Intelligence report for the bar I work for part time.
author: Sloan St. John
---

