---
theme: jekyll-theme-minimal
title: Sloan's Homepage
description: In this project I am building a Business Intelligence report for the bar I work for part time.
layout: default
author: Sloan St. John
---

